persistence true
persistence_location /mosquitto/data/
log_dest stdout

# TCP listener for IoT hardware (ESP32)
listener 1883
protocol mqtt

# WebSocket listener for Next.js frontend
listener 8083
protocol websockets

allow_anonymous true
